---
profiles::base::sysctl_settings:
  kernel.msgmnb:
    value : '65536'
  kernel.msgmax:
    value : '65536'
  kernel.shmmax:
    value : '2588483584'
  kernel.shmall:
    value : '2097152'
  fs.file-max:
    value : '6815744'
  net.ipv4.tcp_keepalive_time:
    value : '1800'
  net.ipv4.tcp_keepalive_intvl:
    value : '30'
  net.ipv4.tcp_keepalive_probes:
    value : '5'
  net.ipv4.tcp_fin_timeout:
    value : '30'
  kernel.shmmni:
    value : '4096'
  fs.aio-max-nr:
    value : '1048576'
  kernel.sem:
    value : '250 32000 100 128'
  net.ipv4.ip_local_port_range:
    value : '9000 65500'
  net.core.rmem_default:
    value : '262144'
  net.core.rmem_max:
    value : '4194304'
  net.core.wmem_default:
    value : '262144'
  net.core.wmem_max:
    value : '1048576'
profiles::base::sysctl_defaults:
  ensure: present
  permanent: 'yes'
roles::syd_f5_load_balancer::vlans:
  VLAN08:
    vlan_tag:    '08'
    interface:   '1.2'
    description: 'Test VLAN08'
    tag_type:    'tagged'
  VLAN09: {}
  VLAN10: {}
  VLAN11: {}
  VLAN12: {}
  VLAN13: {}
  VLAN14: {}
  VLAN15: {}
  VLAN16: {}
  VLAN17: {}
  VLAN18: {}
  VLAN19: {}
  VLAN20: {}
  VLAN21: {}
  VLAN22:
    ensure: 'absent'
roles::syd_f5_load_balancer::vlans_defaults:
  ensure:    'present'
  vlan_tag:  'auto'
  interface: '1.3'
